[font]
size = 18

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"
[font.bold]
family = "Iosevka Nerd Font"
style = "Regular"
[font.italic]
family = "Iosevka Nerd Font"
style = "Regular"
[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
decorations = "none"

[window.padding]
x = 2
y = 2

[env]
TERM = "xterm-256color"


